// src/templates/component/lit/component.view.js
import { html } from "lit";
import { {COMPONENT_NAME}Theme } from "./css/{camelCaseName}.theme.css";
import { {COMPONENT_NAME}ViewModel } from "./{camelCaseName}.viewmodel";


export class {COMPONENT_NAME}View extends {COMPONENT_NAME}ViewModel {
  static finalizeStyles( styles ) {
    return [...super.finalizeStyles(styles), {COMPONENT_NAME}Theme.cssBase];
  }

  render() {
    return html``;
  }
}

window.customElements.define("{camelCaseName}", {COMPONENT_NAME}View);

// src/templates/component/react/component.view.tsx
import {COMPONENT_NAME}Theme from './css/{camelCaseName}.module.css';
import { type {COMPONENT_NAME}Model } from './{camelCaseName}.model';
import { use{COMPONENT_NAME}ViewModel } from "./{camelCaseName}.viewmodel";


export default function {COMPONENT_NAME}View (props : {COMPONENT_NAME}Model){
  const { {camelCaseName}Title } = use{COMPONENT_NAME}ViewModel(props);

  return (
    <>
      <h1>{ {camelCaseName}Title }</h1>
    </>
  );
}
